CI: use ghcr image for bosh/integration
Prior to this commit the Docker Hub which is no longer updated. This
resulted in the following error:
```
golangci-lint has version 2.1.6 built with go1.24.2 from eabc2638 on 2025-05-04T15:41:19Z

 lint-ing in '/tmp/build/41714804/bosh-dns-release/src/bosh-dns' ...
          with GOOS=linux ...
Error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
Failed executing command with error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
```